if kTranslateMessage then
    kTranslateMessage["REQUEST_DISEASE"]="突发恶疾"
    kTranslateMessage["REQUEST_OTTO_OXG"]="欧西给"
    kTranslateMessage["REQUEST_OTTO_KTHULU"]="古神语"
    kTranslateMessage["REQUEST_OTTO_DDD"]="唢呐演奏"
    kTranslateMessage["REQUEST_OTTO_JB"]="基掰"
    kTranslateMessage["REQUEST_OTTO_STORY"]="《营养》"
    kTranslateMessage["REQUEST_OTTO_FOOD"]="韭菜盒子"
    kTranslateMessage["REQUEST_OTTO_SPEAK"]="负能量"
    kTranslateMessage["REQUEST_XUAN_SPEAK"]="小吠"
    kTranslateMessage["REQUEST_XUAN_WOOF"]="狂吠"
    kTranslateMessage["REQUEST_XUAN_OHOO"]="芜湖"
    kTranslateMessage["REQUEST_XUAN_REA"]="惹啊啊"
    kTranslateMessage["REQUEST_XUAN_AHA"]="啊哈"
    kTranslateMessage["REQUEST_XUAN_STORY"]="《第一个王者》"
end